name: e2e tests
on:
  - push
  - pull_request

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: library/node:16-alpine

    services:
      postgres:
        image: library/postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install git for jest-badges-action
        run: apk --no-cache add git

      - name: Config git
        run: git config --global --add safe.directory '*'

      - name: Check out repository code
        uses: actions/checkout@v3.1.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test-ci
        env:
          CONNECTION_STRING: 'postgresql://postgres:postgres@postgres:5432'

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest